dashboardFailFontColor: '#55557f'
dashboardFailFontFamily: Arial
dashboardFailFontItalic: false
dashboardFailFontPointSize: 16
dashboardFailFontStrikeOut: false
dashboardFailFontUnderline: false
dashboardFailFontWeight: 75
dashboardFailText: '{{GAME_IP}} - FAIL'
dashboardFontColor: '#ffffff'
dashboardFontFamily: Arial
dashboardFontItalic: false
dashboardFontPointSize: 22
dashboardFontStrikeOut: false
dashboardFontUnderline: false
dashboardFontWeight: 75
dashboardNormalText: '{{GAME_IP}}'
dashboardPosX: 500
dashboardPosY: 50
dashboardSuccessFontColor: '#ff0000'
dashboardSuccessFontFamily: Arial
dashboardSuccessFontItalic: false
dashboardSuccessFontPointSize: 20
dashboardSuccessFontStrikeOut: false
dashboardSuccessFontUnderline: false
dashboardSuccessFontWeight: 75
dashboardSuccessText: "{{GAME_IP}} - \u2605\u2605\u2605\u2606 OK \u2606\u2605\u2605\
  \u2605"
dashboardTimer: HIDE
firewallPolicy: B
firewallRuleIp: '34.1.1.1-34.117.122.5

  34.117.122.7-34.255.255.255

  35.1.1.1-35.255.255.255

  104.1.1.1-104.255.255.255

  158.1.1.1-158.255.255.255'
gameCreateCycleSec: 90
gameCreateNumber: 1
gameJoinAfterSec: 30
gameNamePrefix: SBW
gamePassword: '1004'
programPath: C:\Program Files (x86)\Diablo II Resurrected\D2R.exe
targetIp: 37.244.11.59
