dashboardFailFontColor: '#55557f'
dashboardFailFontFamily: Arial
dashboardFailFontItalic: false
dashboardFailFontPointSize: 16
dashboardFailFontStrikeOut: false
dashboardFailFontUnderline: false
dashboardFailFontWeight: 75
dashboardFailText: '{{GAME_IP}} - FAIL'
dashboardFontColor: '#ffffff'
dashboardFontFamily: Arial
dashboardFontItalic: false
dashboardFontPointSize: 22
dashboardFontStrikeOut: false
dashboardFontUnderline: false
dashboardFontWeight: 75
dashboardNormalText: '{{GAME_IP}}'
dashboardPosX: 500
dashboardPosY: 50
dashboardSuccessFontColor: '#ff0000'
dashboardSuccessFontFamily: Arial
dashboardSuccessFontItalic: false
dashboardSuccessFontPointSize: 20
dashboardSuccessFontStrikeOut: false
dashboardSuccessFontUnderline: false
dashboardSuccessFontWeight: 75
dashboardSuccessText: "{{GAME_IP}} - \u2605\u2605\u2605\u2606 OK \u2606\u2605\u2605\
  \u2605"
dashboardTimer: HIDE
firewallPolicy: B
firewallRuleIp: '24.106.1.1-34.95.128.255

  34.96.1.1-34.117.122.5

  34.117.122.7-35.197.255.255

  35.198.64.1-35.199.63.255

  35.199.128.1-35.247.191.255

  35.248.1.1-137.221.105.151

  158.115.1.1-158.115.255.255'
gameCreateCycleSec: 90
gameCreateNumber: 1
gameJoinAfterSec: 30
gameNamePrefix: SBW
gamePassword: '1004'
programPath: C:\Program Files (x86)\Diablo II Resurrected\D2R.exe
targetIp: 37.244.11.59
